/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuditControllerV1ActionsV1200Item,
  AuditControllerV1ListV1Params,
  AuditPage
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getAudit = () => {
const auditControllerV1ListV1 = (
    params?: AuditControllerV1ListV1Params,
 ) => {
      return customInstance<AuditPage>(
      {url: `/v1/audit`, method: 'GET',
        params
    },
      );
    }
  const auditControllerV1ActionsV1 = (
    
 ) => {
      return customInstance<AuditControllerV1ActionsV1200Item[]>(
      {url: `/v1/audit/actions`, method: 'GET'
    },
      );
    }
  return {auditControllerV1ListV1,auditControllerV1ActionsV1}};
export type AuditControllerV1ListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAudit>['auditControllerV1ListV1']>>>
export type AuditControllerV1ActionsV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAudit>['auditControllerV1ActionsV1']>>>
