/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateUserBody,
  SetPasswordBody,
  UserItem
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getUsers = () => {
const usersControllerV1ListV1 = (
    
 ) => {
      return customInstance<UserItem[]>(
      {url: `/v1/users`, method: 'GET'
    },
      );
    }
  const usersControllerV1CreateV1 = (
    createUserBody: CreateUserBody,
 ) => {
      return customInstance<UserItem>(
      {url: `/v1/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserBody
    },
      );
    }
  const usersControllerV1SetPasswordV1 = (
    userGuid: string,
    setPasswordBody: SetPasswordBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setPasswordBody
    },
      );
    }
  const usersControllerV1DeleteV1 = (
    userGuid: string,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}`, method: 'DELETE'
    },
      );
    }
  return {usersControllerV1ListV1,usersControllerV1CreateV1,usersControllerV1SetPasswordV1,usersControllerV1DeleteV1}};
export type UsersControllerV1ListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1ListV1']>>>
export type UsersControllerV1CreateV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1CreateV1']>>>
export type UsersControllerV1SetPasswordV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1SetPasswordV1']>>>
export type UsersControllerV1DeleteV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1DeleteV1']>>>
