/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateUserBody,
  SetPasswordBody,
  SetQuotaBody,
  SetUserStatusBody,
  UpdateUserBody,
  UsageItem,
  UserItem,
  UserPage,
  UsersControllerV1ListV1Params
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getUsers = () => {
const usersControllerV1ListV1 = (
    params?: UsersControllerV1ListV1Params,
 ) => {
      return customInstance<UserPage>(
      {url: `/v1/users`, method: 'GET',
        params
    },
      );
    }
  const usersControllerV1CreateV1 = (
    createUserBody: CreateUserBody,
 ) => {
      return customInstance<UserItem>(
      {url: `/v1/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserBody
    },
      );
    }
  const usersControllerV1UpdateV1 = (
    userGuid: string,
    updateUserBody: UpdateUserBody,
 ) => {
      return customInstance<UserItem>(
      {url: `/v1/users/${userGuid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserBody
    },
      );
    }
  const usersControllerV1DeleteV1 = (
    userGuid: string,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}`, method: 'DELETE'
    },
      );
    }
  const usersControllerV1SetStatusV1 = (
    userGuid: string,
    setUserStatusBody: SetUserStatusBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setUserStatusBody
    },
      );
    }
  const usersControllerV1SetQuotaV1 = (
    userGuid: string,
    setQuotaBody: SetQuotaBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}/quota`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setQuotaBody
    },
      );
    }
  const usersControllerV1UsageV1 = (
    userGuid: string,
 ) => {
      return customInstance<UsageItem>(
      {url: `/v1/users/${userGuid}/usage`, method: 'GET'
    },
      );
    }
  const usersControllerV1SetPasswordV1 = (
    userGuid: string,
    setPasswordBody: SetPasswordBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/users/${userGuid}/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setPasswordBody
    },
      );
    }
  return {usersControllerV1ListV1,usersControllerV1CreateV1,usersControllerV1UpdateV1,usersControllerV1DeleteV1,usersControllerV1SetStatusV1,usersControllerV1SetQuotaV1,usersControllerV1UsageV1,usersControllerV1SetPasswordV1}};
export type UsersControllerV1ListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1ListV1']>>>
export type UsersControllerV1CreateV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1CreateV1']>>>
export type UsersControllerV1UpdateV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1UpdateV1']>>>
export type UsersControllerV1DeleteV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1DeleteV1']>>>
export type UsersControllerV1SetStatusV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1SetStatusV1']>>>
export type UsersControllerV1SetQuotaV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1SetQuotaV1']>>>
export type UsersControllerV1UsageV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1UsageV1']>>>
export type UsersControllerV1SetPasswordV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerV1SetPasswordV1']>>>
