services:
  postgres:
    image: postgres:17-alpine
    container_name: storage-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "10400:5432"
    restart: on-failure

  valkey:
    image: valkey/valkey:8-alpine
    container_name: storage-valkey
    ports:
      - "10401:6379"
    command: [ "valkey-server", "--appendonly", "yes" ]
    restart: on-failure

volumes:
  postgres-data:
