/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { AccessKeyItemStatus } from './accessKeyItemStatus';

export interface AccessKeyItem {
  accessKeyId: string;
  userGuid: string;
  /** @nullable */
  description?: string | null;
  status: AccessKeyItemStatus;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  lastUsedAt?: string | null;
  createdAt: string;
}
