/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type AuditEntryAction = typeof AuditEntryAction[keyof typeof AuditEntryAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditEntryAction = {
  userlogin: 'user.login',
  usercreate: 'user.create',
  userupdate: 'user.update',
  'userset-password': 'user.set-password',
  'userset-status': 'user.set-status',
  'userset-quota': 'user.set-quota',
  userdelete: 'user.delete',
  bucketcreate: 'bucket.create',
  bucketdelete: 'bucket.delete',
  'bucketset-acl': 'bucket.set-acl',
  'bucketset-versioning': 'bucket.set-versioning',
  'bucketset-quota': 'bucket.set-quota',
  'bucketset-grant': 'bucket.set-grant',
  'bucketremove-grant': 'bucket.remove-grant',
  'bucketset-policy': 'bucket.set-policy',
  'bucketdelete-policy': 'bucket.delete-policy',
  objectupload: 'object.upload',
  objectdownload: 'object.download',
  objectdelete: 'object.delete',
  'objectdelete-prefix': 'object.delete-prefix',
  'objectcreate-folder': 'object.create-folder',
  objectcopy: 'object.copy',
  objectmove: 'object.move',
  objectpresign: 'object.presign',
  'access-keycreate': 'access-key.create',
  'access-keyset-status': 'access-key.set-status',
  'access-keydelete': 'access-key.delete',
} as const;
