/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { AuditControllerV1ListV1Action } from './auditControllerV1ListV1Action';

export type AuditControllerV1ListV1Params = {
action?: AuditControllerV1ListV1Action;
userGuid?: string;
bucketName?: string;
page?: number;
limit?: number;
};
