/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { AuditEntryAction } from './auditEntryAction';
import type { AuditEntryResult } from './auditEntryResult';
import type { AuditEntryDetail } from './auditEntryDetail';

export interface AuditEntry {
  guid: string;
  action: AuditEntryAction;
  result: AuditEntryResult;
  /** @nullable */
  userGuid?: string | null;
  /** @nullable */
  userEmail?: string | null;
  /** @nullable */
  bucketName?: string | null;
  /** @nullable */
  objectKey?: string | null;
  /** @nullable */
  targetGuid?: string | null;
  /** @nullable */
  sourceIp?: string | null;
  /** @nullable */
  userAgent?: string | null;
  /**
   * Operation payload with secrets redacted
   * @nullable
   */
  detail: AuditEntryDetail;
  createdAt: string;
}
