/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type BucketForbiddenErrorCode = typeof BucketForbiddenErrorCode[keyof typeof BucketForbiddenErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BucketForbiddenErrorCode = {
  permission_denied: 'permission_denied',
} as const;
