/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type BucketItemAcl = typeof BucketItemAcl[keyof typeof BucketItemAcl];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BucketItemAcl = {
  private: 'private',
  'public-read': 'public-read',
  'public-read-write': 'public-read-write',
  'authenticated-read': 'authenticated-read',
} as const;
