/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { BucketItemAcl } from './bucketItemAcl';
import type { BucketItemVersioning } from './bucketItemVersioning';

export interface BucketItem {
  guid: string;
  name: string;
  ownerUserGuid: string;
  region: string;
  acl: BucketItemAcl;
  versioning: BucketItemVersioning;
  /**
   * Storage limit in bytes; null means unlimited
   * @nullable
   */
  quotaBytes: number | null;
  createdAt: string;
}
