/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type BucketNotFoundErrorCode = typeof BucketNotFoundErrorCode[keyof typeof BucketNotFoundErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BucketNotFoundErrorCode = {
  bucket_not_found: 'bucket_not_found',
} as const;
