/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type BucketGrantItemPermissionsItem = typeof BucketGrantItemPermissionsItem[keyof typeof BucketGrantItemPermissionsItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BucketGrantItemPermissionsItem = {
  read: 'read',
  write: 'write',
  delete: 'delete',
  manage: 'manage',
} as const;
