/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { BucketDetailAcl } from './bucketDetailAcl';
import type { BucketDetailVersioning } from './bucketDetailVersioning';
import type { UsageItem } from './usageItem';

export interface BucketDetail {
  guid: string;
  name: string;
  ownerUserGuid: string;
  region: string;
  acl: BucketDetailAcl;
  versioning: BucketDetailVersioning;
  /**
   * Storage limit in bytes; null means unlimited
   * @nullable
   */
  quotaBytes: number | null;
  createdAt: string;
  usage: UsageItem;
}
