/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export interface CopyObjectBody {
  /** Key to copy from; a trailing slash copies the whole folder */
  sourceKey: string;
  targetKey: string;
  /** Defaults to the same bucket */
  targetBucket?: string;
  /** Removes the source afterwards, i.e. a rename */
  move?: boolean;
}
