/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type CreateUserBadRequestErrorCode = typeof CreateUserBadRequestErrorCode[keyof typeof CreateUserBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserBadRequestErrorCode = {
  email_already_used: 'email_already_used',
} as const;
