/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type CreateBucketBadRequestErrorCode = typeof CreateBucketBadRequestErrorCode[keyof typeof CreateBucketBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBucketBadRequestErrorCode = {
  bucket_already_exists: 'bucket_already_exists',
  invalid_bucket_name: 'invalid_bucket_name',
} as const;
