/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type DeleteUserBadRequestErrorCode = typeof DeleteUserBadRequestErrorCode[keyof typeof DeleteUserBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUserBadRequestErrorCode = {
  last_admin: 'last_admin',
} as const;
