/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type DeleteBucketBadRequestErrorCode = typeof DeleteBucketBadRequestErrorCode[keyof typeof DeleteBucketBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteBucketBadRequestErrorCode = {
  bucket_not_empty: 'bucket_not_empty',
} as const;
