/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export interface DeleteObjectResponse {
  /** Keys removed, or hidden behind a delete marker */
  deletedCount: number;
  /** Keys that could not be removed */
  failedKeys: string[];
}
