/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export interface ObjectItem {
  key: string;
  size: number;
  etag: string;
  /** @nullable */
  contentType?: string | null;
  versionId: string;
  lastModified: string;
}
