/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type ObjectNotFoundErrorCode = typeof ObjectNotFoundErrorCode[keyof typeof ObjectNotFoundErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectNotFoundErrorCode = {
  object_not_found: 'object_not_found',
  version_not_found: 'version_not_found',
  bucket_not_found: 'bucket_not_found',
} as const;
