/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type ObjectsControllerV1ListV1Params = {
/**
 * Only keys starting with this prefix
 */
prefix?: string;
/**
 * Collapses keys into folders, typically "/"
 */
delimiter?: string;
/**
 * @minimum 1
 */
maxKeys?: number;
continuationToken?: string;
};
