/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type ObjectsControllerV1DownloadV1Params = {
key: string;
/**
 * Defaults to the newest version
 */
versionId?: string;
};
