/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type ObjectTooLargeErrorCode = typeof ObjectTooLargeErrorCode[keyof typeof ObjectTooLargeErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectTooLargeErrorCode = {
  payload_too_large: 'payload_too_large',
} as const;
