/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type ObjectBadRequestErrorCode = typeof ObjectBadRequestErrorCode[keyof typeof ObjectBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectBadRequestErrorCode = {
  invalid_key: 'invalid_key',
  object_already_exists: 'object_already_exists',
  bad_digest: 'bad_digest',
  bucket_quota_exceeded: 'bucket_quota_exceeded',
  user_quota_exceeded: 'user_quota_exceeded',
  no_usable_access_key: 'no_usable_access_key',
} as const;
