/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type PolicyBadRequestErrorCode = typeof PolicyBadRequestErrorCode[keyof typeof PolicyBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PolicyBadRequestErrorCode = {
  invalid_policy_document: 'invalid_policy_document',
} as const;
