/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type PolicyNotFoundErrorCode = typeof PolicyNotFoundErrorCode[keyof typeof PolicyNotFoundErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PolicyNotFoundErrorCode = {
  policy_not_found: 'policy_not_found',
  bucket_not_found: 'bucket_not_found',
} as const;
