/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export interface PresignObjectBody {
  key: string;
  /**
   * @minimum 1
   * @maximum 604800
   */
  expiresIn?: number;
  versionId?: string;
}
