/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { SetBucketGrantBodyPermissionsItem } from './setBucketGrantBodyPermissionsItem';

export interface SetBucketGrantBody {
  userGuid: string;
  permissions: SetBucketGrantBodyPermissionsItem[];
}
