/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { SetBucketVersioningBodyVersioning } from './setBucketVersioningBodyVersioning';

export interface SetBucketVersioningBody {
  /** S3 has no way back to "disabled" once versioning was enabled */
  versioning: SetBucketVersioningBodyVersioning;
}
