/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

/**
 * S3 has no way back to "disabled" once versioning was enabled
 */
export type SetBucketVersioningBodyVersioning = typeof SetBucketVersioningBodyVersioning[keyof typeof SetBucketVersioningBodyVersioning];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetBucketVersioningBodyVersioning = {
  disabled: 'disabled',
  enabled: 'enabled',
  suspended: 'suspended',
} as const;
