/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export type SetPasswordBadRequestErrorCode = typeof SetPasswordBadRequestErrorCode[keyof typeof SetPasswordBadRequestErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetPasswordBadRequestErrorCode = {
  invalid_current_password: 'invalid_current_password',
} as const;
