/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */

export interface UsageItem {
  /** Keys whose newest version is not a delete marker */
  objectCount: number;
  /** Stored versions carrying a payload */
  versionCount: number;
  /** Bytes of all stored versions */
  versionBytes: number;
  /** Bytes held by unfinished multipart uploads */
  multipartBytes: number;
  /** Bytes counted against the quota */
  totalBytes: number;
}
