/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type { UserItemRole } from './userItemRole';

export interface UserItem {
  guid: string;
  email: string;
  /** @nullable */
  name?: string | null;
  role: UserItemRole;
  /** @nullable */
  lastLoginAt?: string | null;
  createdAt: string;
}
