/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../../customInstance';



  export const getApp = () => {
const appControllerStatus = (
    
 ) => {
      return customInstance<void>(
      {url: `/`, method: 'GET'
    },
      );
    }
  return {appControllerStatus}};
export type AppControllerStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApp>['appControllerStatus']>>>
