/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  BucketUsageItem,
  UserUsageItem
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getUsage = () => {
const usageControllerV1BucketsV1 = (
    
 ) => {
      return customInstance<BucketUsageItem[]>(
      {url: `/v1/usage/buckets`, method: 'GET'
    },
      );
    }
  const usageControllerV1UsersV1 = (
    
 ) => {
      return customInstance<UserUsageItem[]>(
      {url: `/v1/usage/users`, method: 'GET'
    },
      );
    }
  return {usageControllerV1BucketsV1,usageControllerV1UsersV1}};
export type UsageControllerV1BucketsV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsage>['usageControllerV1BucketsV1']>>>
export type UsageControllerV1UsersV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsage>['usageControllerV1UsersV1']>>>
