/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  AccessKeyPage,
  AccessKeysControllerV1ListV1Params,
  CreateAccessKeyBody,
  CreatedAccessKey,
  SetAccessKeyStatusBody
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getAccessKeys = () => {
const accessKeysControllerV1ListV1 = (
    params?: AccessKeysControllerV1ListV1Params,
 ) => {
      return customInstance<AccessKeyPage>(
      {url: `/v1/access-keys`, method: 'GET',
        params
    },
      );
    }
  const accessKeysControllerV1CreateV1 = (
    createAccessKeyBody: CreateAccessKeyBody,
 ) => {
      return customInstance<CreatedAccessKey>(
      {url: `/v1/access-keys`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessKeyBody
    },
      );
    }
  const accessKeysControllerV1SetStatusV1 = (
    accessKeyId: string,
    setAccessKeyStatusBody: SetAccessKeyStatusBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/access-keys/${accessKeyId}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setAccessKeyStatusBody
    },
      );
    }
  const accessKeysControllerV1DeleteV1 = (
    accessKeyId: string,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/access-keys/${accessKeyId}`, method: 'DELETE'
    },
      );
    }
  return {accessKeysControllerV1ListV1,accessKeysControllerV1CreateV1,accessKeysControllerV1SetStatusV1,accessKeysControllerV1DeleteV1}};
export type AccessKeysControllerV1ListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessKeys>['accessKeysControllerV1ListV1']>>>
export type AccessKeysControllerV1CreateV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessKeys>['accessKeysControllerV1CreateV1']>>>
export type AccessKeysControllerV1SetStatusV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessKeys>['accessKeysControllerV1SetStatusV1']>>>
export type AccessKeysControllerV1DeleteV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessKeys>['accessKeysControllerV1DeleteV1']>>>
