/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  PolicyResponse,
  SetPolicyBody
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getPolicies = () => {
const policiesControllerV1GetV1 = (
    bucketName: string,
 ) => {
      return customInstance<PolicyResponse>(
      {url: `/v1/buckets/${bucketName}/policy`, method: 'GET'
    },
      );
    }
  const policiesControllerV1SetV1 = (
    bucketName: string,
    setPolicyBody: SetPolicyBody,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/buckets/${bucketName}/policy`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setPolicyBody
    },
      );
    }
  const policiesControllerV1DeleteV1 = (
    bucketName: string,
 ) => {
      return customInstance<unknown>(
      {url: `/v1/buckets/${bucketName}/policy`, method: 'DELETE'
    },
      );
    }
  return {policiesControllerV1GetV1,policiesControllerV1SetV1,policiesControllerV1DeleteV1}};
export type PoliciesControllerV1GetV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['policiesControllerV1GetV1']>>>
export type PoliciesControllerV1SetV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['policiesControllerV1SetV1']>>>
export type PoliciesControllerV1DeleteV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['policiesControllerV1DeleteV1']>>>
