/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListObjectsResponse,
  ObjectVersionItem,
  ObjectsControllerV1ListV1Params,
  ObjectsControllerV1ListVersionsV1Params
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getObjects = () => {
const objectsControllerV1ListV1 = (
    bucketName: string,
    params?: ObjectsControllerV1ListV1Params,
 ) => {
      return customInstance<ListObjectsResponse>(
      {url: `/v1/buckets/${bucketName}/objects`, method: 'GET',
        params
    },
      );
    }
  const objectsControllerV1ListVersionsV1 = (
    bucketName: string,
    params: ObjectsControllerV1ListVersionsV1Params,
 ) => {
      return customInstance<ObjectVersionItem[]>(
      {url: `/v1/buckets/${bucketName}/objects/versions`, method: 'GET',
        params
    },
      );
    }
  return {objectsControllerV1ListV1,objectsControllerV1ListVersionsV1}};
export type ObjectsControllerV1ListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getObjects>['objectsControllerV1ListV1']>>>
export type ObjectsControllerV1ListVersionsV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getObjects>['objectsControllerV1ListVersionsV1']>>>
