/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Storage API
 * Management API for buckets, access keys, policies and the file browser
 * OpenAPI spec version: 1.0.0
 */
import type {
  IdentityResponse,
  LoginBody,
  RefreshBody,
  TokensResponse
} from '.././models';

import { customInstance } from '../../customInstance';



  export const getAuth = () => {
const authControllerV1LoginV1 = (
    loginBody: LoginBody,
 ) => {
      return customInstance<TokensResponse>(
      {url: `/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginBody
    },
      );
    }
  const authControllerV1RefreshV1 = (
    refreshBody: RefreshBody,
 ) => {
      return customInstance<TokensResponse>(
      {url: `/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshBody
    },
      );
    }
  const authControllerV1LogoutV1 = (
    refreshBody: RefreshBody,
 ) => {
      return customInstance<void>(
      {url: `/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshBody
    },
      );
    }
  const authControllerV1MeV1 = (
    
 ) => {
      return customInstance<IdentityResponse>(
      {url: `/v1/auth/me`, method: 'GET'
    },
      );
    }
  return {authControllerV1LoginV1,authControllerV1RefreshV1,authControllerV1LogoutV1,authControllerV1MeV1}};
export type AuthControllerV1LoginV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authControllerV1LoginV1']>>>
export type AuthControllerV1RefreshV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authControllerV1RefreshV1']>>>
export type AuthControllerV1LogoutV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authControllerV1LogoutV1']>>>
export type AuthControllerV1MeV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authControllerV1MeV1']>>>
